[versions]
accompanistNavigationMaterial = "0.37.3"
accompanistSystemuicontrollerVersion = "0.27.0"
agp = "8.10.1"
androidWaveRecorder = "2.1.0"
browser = "1.8.0"
composeVectorizeCore = "1.0.2"
hilt = "2.56.2"
hiltCompiler = "2.56.2"
hiltCompose = "1.2.0"
jna = "5.13.0"
material = "1.11.0"
materialIconsCore = "1.7.3"
multiplatformSettings = "1.3.0"
navCompose = "2.8.3"
sqldelight = "1.5.5"
sqldelightCoroutines = "1.5.4"
kotlinxDatetime = "0.4.0"
atomicfu = "0.17.3"
composeMultiplatform = "1.8.0"
kotlin = "2.1.20"
compose-material3 = "1.3.1"
activityKtx = "1.9.3"
animationAndroid = "1.7.6"
kotlinxSerializationJson = "1.5.1"
app-icon = "1.2.6"
appcompat = "1.7.0"
koin = "4.1.0"
splashscreen = "1.0.1"
datastore = "1.1.1"
napier = "2.5.0"
androidx-activityCompose = "1.10.1"
compose-ui-tooling = "1.6.4"
navigation-compose = "2.9.0-beta03"
kotlinx-coroutines = "1.10.2"
core-ktx = "1.16.0"
androidx-lifecycle = "2.9.1"

# Android SDK
android-compileSdk = "36"
android-minSdk = "26"
android-targetSdk = "36"

documentfile = "1.1.0"

[libraries]
# Non-UI dependencies
accompanist-navigation-material = { module = "com.google.accompanist:accompanist-navigation-material", version.ref = "accompanistNavigationMaterial" }
android-wave-recorder = { module = "com.github.squti:Android-Wave-Recorder", version.ref = "androidWaveRecorder" }
androidx-browser = { module = "androidx.browser:browser", version.ref = "browser" }
compose-vectorize-core = { module = "dev.sergiobelda.compose.vectorize:compose-vectorize-core", version.ref = "composeVectorizeCore" }
google-accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanistSystemuicontrollerVersion" }
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-android-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hiltCompiler" }
hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hiltCompose" }
hilt-compiler = { group = "androidx.hilt", name = "hilt-compiler", version.ref = "hiltCompose" }
jetbrains-atomicfu = { module = "org.jetbrains.kotlinx:atomicfu", version.ref = "atomicfu" }
jna = { module = "net.java.dev.jna:jna", version.ref = "jna" }
material = { module = "com.google.android.material:material", version.ref = "material" }
material-icons-core = { module = "org.jetbrains.compose.material:material-icons-core", version.ref = "materialIconsCore" }
multiplatform-settings = { module = "com.russhwolf:multiplatform-settings", version.ref = "multiplatformSettings" }
multiplatform-settings-coroutines = { module = "com.russhwolf:multiplatform-settings-coroutines", version.ref = "multiplatformSettings" }
navigation-compose = { module = "org.jetbrains.androidx.navigation:navigation-compose", version.ref = "navigation-compose" }
kotlinx-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "kotlinxDatetime" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
androidx-lifecycle-runtime-compose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel", version.ref = "androidx-lifecycle" }

# UI dependencies
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }
androidx-compose-ui-util = { module = "androidx.compose.ui:ui-util", version.ref = "compose-ui-tooling" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose-ui-tooling" }
androidx-compose-ui-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose-ui-tooling" }
androidx-core = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
androidx-compose-documentfile = { module = "androidx.documentfile:documentfile", version.ref = "documentfile" }

datastore = { module = "androidx.datastore:datastore", version.ref = "datastore" }
datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }

# Plugin dependencies
hilt-android-gradle-plugin = { group = "com.google.dagger", name = "hilt-android-gradle-plugin", version.ref = "hiltCompiler" }
atomicfu-gradle-plugin = { group = "org.jetbrains.kotlinx", name = "atomicfu-gradle-plugin", version.ref = "atomicfu" }
activity-ktx = { group = "androidx.activity", name = "activity-ktx", version.ref = "activityKtx" }
animation-android = { group = "androidx.compose.animation", name = "animation-android", version.ref = "animationAndroid" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }

# Koin
koin-androidx-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koin" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-test = { module = "io.insert-koin:koin-test", version.ref = "koin" }
koin-compose-viewmodel = { module = "io.insert-koin:koin-compose-viewmodel", version.ref = "koin" }

# SQLDelight
sqldelight-runtime = { group = "com.squareup.sqldelight", name = "runtime", version.ref = "sqldelight" }
sqldelight-coroutines = { group = "com.squareup.sqldelight", name = "coroutines-extensions", version.ref = "sqldelight" }
sqldelight-android-driver = { group = "com.squareup.sqldelight", name = "android-driver", version.ref = "sqldelight" }
sqldelight-native-driver = { group = "com.squareup.sqldelight", name = "native-driver", version.ref = "sqldelight" }
sqldelight-gradle-plugin = { group = "com.squareup.sqldelight", name = "gradle-plugin", version.ref = "sqldelight" }

# Splash
core-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "splashscreen" }


napier = { module = "io.github.aakira:napier", version.ref = "napier" }

[plugins]
androidLibrary = { id = "com.android.library", version.ref = "agp" }
androidApplication = { id = "com.android.application", version.ref = "agp" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinxSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
app-icon = { id = "io.github.qamarelsafadi.kmp.app.icon.generator", version.ref = "app-icon" }
